add missing header
src/baby_bsp.c:110:3: error: implicit declaration of function 'stat' [-Werror=implicit-function-declaration]
src/baby_bsp.c:110:3: error: implicit declaration of function 'S_ISCHR' [-Werror=implicit-function-declaration]